# Generated by Django 4.2.23 on 2025-07-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoatividade',
            name='sigla_complementar',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
