# Generated by Django 4.2.23 on 2025-07-05 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0003_alter_tipoatividade_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('residente', models.CharField(max_length=255)),
                ('setores', models.CharField(max_length=255)),
                ('preceptores', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscalaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('turno', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escala.tipoatividade')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='escala.escalamensal')),
            ],
        ),
    ]
