# Generated by Django 4.2.23 on 2025-07-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0004_escalamensal_escaladia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='escalamensal',
            name='preceptores',
        ),
        migrations.RemoveField(
            model_name='escalamensal',
            name='setores',
        ),
        migrations.AddField(
            model_name='escalamensal',
            name='preceptores',
            field=models.ManyToManyField(related_name='escalas', to='escala.preceptor'),
        ),
        migrations.AddField(
            model_name='escalamensal',
            name='setores',
            field=models.ManyToManyField(related_name='escalas', to='escala.setor'),
        ),
    ]
